### ISSUE TITLE
What is the http endpoint (curl query) to fetch the latest blockheight for the docker rosetta mainnet node?

### ISSUE THREAD

**Issue by shassal** [Kava-Labs/rosetta-kava#54]
I set up the kava rosetta mainnet node in the server. But not able to run the curl queries (http endpoints). Can anyone help me with the curl query to fetch the latest blockheight for the docker rosetta mainnet node?

**Comment by nddeluca** [comment]
You can check the /network/status endpoint to get the `.sync_status.current_index` which is the latest height.

Here is an example if running rosetta on port 8000 and kava-mainnet.
```
curl -X 'POST' \
  'http://localhost:8000/network/status' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "network_identifier": {
    "blockchain": "Kava",
    "network": "kava-mainnet"
  },
  "metadata": {}
}'
```

**Comment by shassal** [comment]
yaa, that worked, thanks.

**Comment by shassal** [comment]
Completed

**Comment by shassal** [comment]
What is the curl query to fetch the transactions by transaction hash?

**Comment by nddeluca** [comment]
Rosetta does not include the ability to query by transaction hash -- it requires users to build their own indexes to search.  The kava node endpoints would have to be used.
